# Generated by Django 4.0.6 on 2022-07-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/Avatar'),
        ),
    ]
