# Generated by Django 4.1 on 2022-08-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_phonenumber_user_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='index',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
