# Generated by Django 4.1 on 2022-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_index_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason',
            field=models.CharField(choices=[('u', 'university'), ('d', 'highschool'), ('a', 'Friend'), ('g', 'game'), ('o', 'other')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
