# Generated by Django 4.1 on 2022-08-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reason',
            field=models.CharField(choices=[('u', 'university'), ('h', 'highschool'), ('a', 'Friend'), ('g', 'game'), ('o', 'other'), ('f', 'family')], max_length=1),
        ),
    ]
