# Generated by Django 4.1 on 2022-08-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='reason',
            field=models.CharField(choices=[('u', 'university'), ('h', 'highschool'), ('a', 'Friend'), ('g', 'game'), ('s', 'school'), ('o', 'other'), ('f', 'family'), ('i', 'instagram')], max_length=1),
        ),
    ]
