# Generated by Django 4.1 on 2022-08-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_city_east_city_north'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='east',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='city',
            name='north',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
