# Generated by Django 4.1 on 2022-08-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_city_east'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='north',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
