# Generated by Django 4.1 on 2022-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_city_north'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Rating',
            field=models.IntegerField(default=1),
        ),
    ]
