# Generated by Django 4.1 on 2022-08-19 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
