# Generated by Django 4.1 on 2022-08-19 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Friends',
        ),
        migrations.AddField(
            model_name='user',
            name='Friends',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
