# Generated by Django 4.1 on 2023-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_user_friends_remove_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reason',
            field=models.CharField(choices=[('u', 'sutech'), ('h', 'highschool'), ('a', 'Friend'), ('g', 'game'), ('s', 'school'), ('o', 'other'), ('f', 'family'), ('i', 'instagram'), ('y', 'iust')], max_length=1),
        ),
    ]
