# Generated by Django 4.1 on 2022-08-19 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_user_friends_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Friends',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
