# Generated by Django 4.1 on 2022-09-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
