# Generated by Django 4.1 on 2022-08-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Friends',
        ),
    ]
